ingressVersion: nginx
envdtap: acc

ingress:
  - rules:
      - host: testapp-acc.solvops.solvinity.com
        paths:
          - backend: 
            servicename: coffeebean
            serviceport: '80'
            path: /

tls:
  hosts:
  - testapp-acc.solvops.solvinity.com

ingressDomains:
  - testapp-acc.solvops.solvinity.com
