ingressVersion: nginx
envdtap: prod

ingress:
  - rules:
      - host: testapp-prd.solvops.solvinity.com
        paths:
          - backend: 
            servicename: coffeebean
            serviceport: '80'
            path: /

tls:
  hosts:
  - testapp-prd.solvops.solvinity.com

ingressDomains:
  - testapp-prd.solvops.solvinity.com          
